name: Flutter Workflow

on:
  
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.0'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/app-release.apk"
          tag: v1.0.${{ github.run_number}}
          token: ${{ secrets.TOKEN }}

      
